In [1]:
import numpy as np

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [14]:
# This inbuild function for Alexandre- Theophile Vandermonde Matrix
print(np.vander([1,2,3,4], increasing=True))
print(np.vander([1,2,3,4], increasing=False))

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [15]:
def vander_matrix(x, increasing=False):
    v_array = None
    try:
        arr = []
        if increasing:
            power = range(0, len(x))
        else:
            power = range(len(x) - 1, -1, -1)
        for elm in x:
            arr.append([elm**p for p in power])
        v_array = np.array(arr)

    except:
        print('Exception occurred.')

    return v_array

print(vander_matrix([1,2,3,4], increasing=True))
print(vander_matrix([1,2,3,4], increasing=False))

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


Write a function to find moving average in an array over a window: 
    
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [21]:
def moving_avg(n, k):
    if len(n) < 3:
        print('Nof elements in {} should be greater than 3.'.format(n))
    for i in range(len(n)-k+1):
        print(round(sum(n[i:i+k])/k, 2))


moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

5.0
4.67
5.67
6.67
9.67
28.67
49.33
72.67
84.0
93.33
116.33
